Create createCustomLobby.py
sousa-andre/lcu-driver pull request #5
Opened 2021-01-27 20:24 UTC by XHXIAIEIN

2021-01-27 21:12 UTC, sousa-andre requested changes
Can you always use single quotes instead of double quotes for strings?

2021-01-27 21:12 UTC, sousa-andre commented on examples/createCustomLobby.py
> +  await creat_lobby(connection)
The coroutine does not exist. Typo.

2021-01-28 03:22 UTC, XHXIAIEIN commented on examples/createCustomLobby.py
> +  await creat_lobby(connection)
Sorry, I'll fix it

2021-01-28 04:59 UTC, XHXIAIEIN commented on examples/createCustomLobby.py
> +  await creat_lobby(connection)
> The coroutine does not exist. Typo.

I modified it, please check again

2021-01-28 09:06 UTC, merged